### ISSUE TITLE
Feature:⚠️ Area change alerts ⚠️

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-detector-Twitter#6]
As a user I would like to see where bots/activity is changing per day. 

As a developer, combined with a nice graph, may be beneficial for marketing purposes and may include our followership. We could use predicted bot locations for this information.

Proposed format for the Area Change Alerts:

⚠️Density Change⚠️
Grand Exchange 18% Increase
Slayer Tower 7% Increase
Hosidius Vinery Beach -5% Decrease
Draynor Village -10% Decrease

**Comment by Ferrariic** [comment]
@extreme4all Can you list why wontfix

**Comment by Ferrariic** [comment]
Edit: change from percentage to # of players

**Comment by extreme4all** [comment]
it is not realistic daily change and it will be highly variable post spam
